project:
  type: website
  output-dir: docs

website:
  title: "Gabriel Andrade-Ponce"
  
  navbar:
    background: "#536878"
    left:
      - href: about/index.qmd
        text: About
      - href: blog/index.qmd
        text: Blog
      - href: publications/index.qmd
        text: Publicaciones
      
    page-footer:
     left: "Copyright 2022, Gabriel Andrade-Ponce"
     right:
      - icon: github
        href: https://github.com/gpandradep
      - icon: twitter
        href: https://twitter.com/Gatorco_AP
     background: "#536878"
    
date-format: "D MMMM YYYY"

format:
  html:
    theme: tango
    css: styles.css
    toc: true
    html-math-method: katex
    include-in-header:
      file: header.html

