project:
  type: website
  output-dir: docs

website:
  title: "Gabriel Andrade-Ponce"
  twitter-card: true
  
  navbar:
    background: "#104E8B"
    left:
      - href: about/index.qmd
        text: Sobre mi
      - href: blog/index.qmd
        text: Blog
      - href: publications/index.qmd
        text: Publicaciones
      
    page-footer:
     left: "Copyright 2022, Gabriel Andrade-Ponce"
     right:
      - icon: github
        href: https://github.com/gpandradep
      - icon: twitter
        href: https://twitter.com/Gatorco_AP
     background: "#536878"
    
date-format: "D MMMM YYYY"

filters:
  - social-share
share:
  permalink: "https://gpandradep.github.io/gpandradep/"
  description: "Página Gabriel Andrade"
  twitter: true
  facebook: true
  reddit: false
  stumble: false
  tumblr: false
  linkedin: true
  email: true
  mastodon: true

format:
  html:
    theme: tango
    css: styles.css
    toc: true
    html-math-method: katex
    include-in-header:
      file: header.html

